all:
  children:
    managers:
      hosts:
        dnd-char-gen-manager:
    workers:
      hosts:
        dnd-char-gen-worker:
    load-balancer:
      hosts:
        dnd-char-gen-nginx:
  
  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: '~/.ssh/id_rsa'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'